'use strict';
export const autoLijst = [
  "Acura", "AlfaRomeo", "Audi", "Bentley", "BMW", "Bugatti", "Buick",
  "Cadillac", "Chevrolet", "Chrysler", "Citroen", "Dacia", "Daewoo",
  "Daihatsu", "Dodge", "Ferrari", "Fiat", "Ford", "Genesis", "GMC",
  "Honda", "Hyundai", "Infiniti", "Isuzu", "Jaguar", "Jeep", "Kia",
  "Koenigsegg", "Lamborghini", "Lancia", "LandRover", "Lexus", "Lincoln",
  "Lotus", "Maserati", "Mazda", "McLaren", "Mercedes", "Mini", "Mitsubishi",
  "Nissan", "Opel", "Pagani", "Peugeot", "Porsche", "Ram", "Renault",
  "RollsRoyce", "Saab", "Seat", "Skoda", "Smart", "SsangYong", "Subaru",
  "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo"
];
export const landen = [
  {"naam": "Nederland", "continent": "Europa", "oppervlakte": 41543, "taal": "Nederlands"},
  {"naam": "Duitsland", "continent": "Europa", "oppervlakte": 357022, "taal": "Duits"},
  {"naam": "Frankrijk", "continent": "Europa", "oppervlakte": 551695, "taal": "Frans"},
  {"naam": "Spanje", "continent": "Europa", "oppervlakte": 505990, "taal": "Spaans"},
  {"naam": "Italie", "continent": "Europa", "oppervlakte": 301340, "taal": "Italiaans"},
  {"naam": "VerenigdKoninkrijk", "continent": "Europa", "oppervlakte": 243610, "taal": "Engels"},
  {"naam": "Belgie", "continent": "Europa", "oppervlakte": 30689, "taal": "Nederlands, Frans, Duits"},
  {"naam": "Rusland", "continent": "Azië", "oppervlakte": 17098242, "taal": "Russisch"},
  {"naam": "China", "continent": "Azië", "oppervlakte": 9596961, "taal": "Mandarijn"},
  {"naam": "Japan", "continent": "Azië", "oppervlakte": 377975, "taal": "Japans"},
  {"naam": "India", "continent": "Azië", "oppervlakte": 3287263, "taal": "Hindi, Engels"},
  {"naam": "ZuidKorea", "continent": "Azië", "oppervlakte": 100210, "taal": "Koreaans"},
  {"naam": "Indonesie", "continent": "Azië", "oppervlakte": 1904569, "taal": "Indonesisch"},
  {"naam": "Vietnam", "continent": "Azië", "oppervlakte": 331212, "taal": "Vietnamees"},
  {"naam": "Thailand", "continent": "Azië", "oppervlakte": 513120, "taal": "Thais"},
  {"naam": "ZuidAfrika", "continent": "Afrika", "oppervlakte": 1221037, "taal": "Afrikaans, Engels, Zulu, Xhosa"},
  {"naam": "Egypte", "continent": "Afrika", "oppervlakte": 1002450, "taal": "Arabisch"},
  {"naam": "Nigeria", "continent": "Afrika", "oppervlakte": 923768, "taal": "Engels"},
  {"naam": "Kenia", "continent": "Afrika", "oppervlakte": 580367, "taal": "Engels, Swahili"},
  {"naam": "Marokko", "continent": "Afrika", "oppervlakte": 710850, "taal": "Arabisch, Berbers"},
  {"naam": "Argentinie", "continent": "Zuid-Amerika", "oppervlakte": 2780400, "taal": "Spaans"},
  {"naam": "Brazilie", "continent": "Zuid-Amerika", "oppervlakte": 8515767, "taal": "Portugees"},
  {"naam": "Colombia", "continent": "Zuid-Amerika", "oppervlakte": 1141748, "taal": "Spaans"},
  {"naam": "Peru", "continent": "Zuid-Amerika", "oppervlakte": 1285216, "taal": "Spaans"},
  {"naam": "Chili", "continent": "Zuid-Amerika", "oppervlakte": 756102, "taal": "Spaans"},
  {"naam": "VerenigdeStaten", "continent": "Noord-Amerika", "oppervlakte": 9833517, "taal": "Engels"},
  {"naam": "Canada", "continent": "Noord-Amerika", "oppervlakte": 9984670, "taal": "Engels, Frans"},
  {"naam": "Mexico", "continent": "Noord-Amerika", "oppervlakte": 1964375, "taal": "Spaans"},
  {"naam": "Cuba", "continent": "Noord-Amerika", "oppervlakte": 109884, "taal": "Spaans"},
  {"naam": "Australie", "continent": "Oceanië", "oppervlakte": 7692024, "taal": "Engels"},
  {"naam": "NieuwZeeland", "continent": "Oceanië", "oppervlakte": 268838, "taal": "Engels, Maori"},
  {"naam": "NieuwGuinea", "continent": "Oceanië", "oppervlakte": 462840, "taal": "Engels, Tok Pisin, Hiri Motu"},
  {"naam": "Algerije", "continent": "Afrika", "oppervlakte": 2381741, "taal": "Arabisch"},
  {"naam": "Tunesie", "continent": "Afrika", "oppervlakte": 163610, "taal": "Arabisch"},
  {"naam": "Ethiopie", "continent": "Afrika", "oppervlakte": 1104300, "taal": "Amhaars"},
  {"naam": "Ghana", "continent": "Afrika", "oppervlakte": 238533, "taal": "Engels"},
  {"naam": "Senegal", "continent": "Afrika", "oppervlakte": 196722, "taal": "Frans"},
  {"naam": "Oekraine", "continent": "Europa", "oppervlakte": 603500, "taal": "Oekraïens"},
  {"naam": "Polen", "continent": "Europa", "oppervlakte": 312696, "taal": "Pools"},
  {"naam": "Hongarije", "continent": "Europa", "oppervlakte": 93028, "taal": "Hongaars"},
  {"naam": "Kazachstan", "continent": "Azië", "oppervlakte": 2724900, "taal": "Kazachs, Russisch"},
  {"naam": "Iran", "continent": "Azië", "oppervlakte": 1648195, "taal": "Perzisch"},
  {"naam": "Pakistan", "continent": "Azië", "oppervlakte": 881913, "taal": "Urdu, Engels"},
  {"naam": "Filipijnen", "continent": "Azië", "oppervlakte": 300000, "taal": "Filipijns, Engels"},
  {"naam": "Bangladesh", "continent": "Azië", "oppervlakte": 147570, "taal": "Bengaals"},
  {"naam": "Venezuela", "continent": "Zuid-Amerika", "oppervlakte": 916445, "taal": "Spaans"},
  {"naam": "Paraguay", "continent": "Zuid-Amerika", "oppervlakte": 406752, "taal": "Spaans, Guaraní"},
  {"naam": "Ecuador", "continent": "Zuid-Amerika", "oppervlakte": 276841, "taal": "Spaans"},
  {"naam": "Bolivia", "continent": "Zuid-Amerika", "oppervlakte": 1098581, "taal": "Spaans"}
];

//console.log(landLijst);
/*const landLijst = [
    "Belgie", "Frankrijk", "Spanje", "Duitsland", "Nederland", "Luxembourg", "Engeland",
    "Zweden", "Dublin", "Iceland", "Turkije", "Marocco", "Tunesie", "Egypte", "Lybia", "Palestina",
    "Algerije", "Dubai", "Portugal", "California", "Japan", "Rusland", "Iran", "Syrie",
    "Dannemark", "Chicago", "Italia", "Polen", "Roemenie", "Zwitserland", "Oostenrijk", "NewYork",
    "Canada", "Mexico", "Cuba", "Brazilie", "Argentina", "Croatia", "Greekenland", "Soedan", "Guinee",
    "Tanzania", "Nigeria", "Philippijn", "China", "Amerika", "Sinegaal", "Zambia", "Namibia", "Madagaskar" 
];*/
  